version: '3.9'

services:

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  airflow-init:
    build: .
    depends_on:
      - postgres
    entrypoint: >
      bash -c "
        airflow db migrate &&
        airflow users create -u admin -p admin -r Admin -f Filip -l Poltoraczyk -e admin@example.com
      "
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - PYTHONPATH=/opt/airflow
      - AIRFLOW__WEBSERVER__SECRET_KEY=some-long-secret-string
    volumes:
      - ./dags:/opt/airflow/dags
      - ./etl:/opt/airflow/etl
      - ./init:/opt/airflow/init
      - ./post:/opt/airflow/post
      - ./utils:/opt/airflow/utils
      - ./data:/opt/airflow/data

  airflow-webserver:
    build: .
    container_name: airflow-webserver
    depends_on:
      - airflow-init
    command: webserver
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - PYTHONPATH=/opt/airflow
      - AIRFLOW__WEBSERVER__SECRET_KEY=some-long-secret-string
    volumes:
      - ./dags:/opt/airflow/dags
      - ./etl:/opt/airflow/etl
      - ./init:/opt/airflow/init
      - ./utils:/opt/airflow/utils
      - ./post:/opt/airflow/post
      - ./data:/opt/airflow/data

  airflow-scheduler:
    build: .
    container_name: airflow-scheduler
    depends_on:
      - airflow-init
    command: scheduler
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - PYTHONPATH=/opt/airflow
      - AIRFLOW__WEBSERVER__SECRET_KEY=some-long-secret-string
    volumes:
      - ./dags:/opt/airflow/dags
      - ./etl:/opt/airflow/etl
      - ./init:/opt/airflow/init
      - ./utils:/opt/airflow/utils
      - ./post:/opt/airflow/post
      - ./data:/opt/airflow/data

  sqlclient:
    image: mcr.microsoft.com/mssql-tools
    container_name: sqlclient
    depends_on:
      - mssql
    stdin_open: true
    tty: true
    entrypoint: /bin/bash

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    expose:
      - 8080

  adminer-proxy:
    image: nginx:alpine
    container_name: adminer-proxy
    ports:
      - "8081:80"
    volumes:
      - ./adminer_redirect.conf:/etc/nginx/conf.d/default.conf
      - ./index.html:/usr/share/nginx/html/index.html
    depends_on:
      - adminer


volumes:
  mssql_data:
  postgres_data:
